name: Docker Build and Publish

on:
  release:
    types: [published]  # 触发条件：创建新Release时运行

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 步骤2：登录Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 步骤3：生成镜像标签
      - name: Generate Image Metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/homework_github_actions_part2

      # 步骤4：构建并推送镜像
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}